osclass:
  image: sjoerd/apache-php7
  volumes:
    - .:/var/www/html
  links:
    - db
  ports:
    - "8333:80"

db:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: osclass
    MYSQL_DATABASE: osclass
    MYSQL_USER: osclass
    MYSQL_PASSWORD: osclass
